// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_visits.sql

package sqlcgen

import (
	"context"
	"time"
)

const countLinkVisits = `-- name: CountLinkVisits :one
SELECT COUNT(*)
FROM link_visits
`

func (q *Queries) CountLinkVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinkVisits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLinkVisit = `-- name: CreateLinkVisit :one
INSERT INTO link_visits (link_id, created_at, ip, user_agent, referer, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateLinkVisitParams struct {
	LinkID    int64
	CreatedAt time.Time
	Ip        string
	UserAgent string
	Referer   string
	Status    int32
}

func (q *Queries) CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLinkVisit,
		arg.LinkID,
		arg.CreatedAt,
		arg.Ip,
		arg.UserAgent,
		arg.Referer,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLinkVisits = `-- name: ListLinkVisits :many
SELECT id, link_id, created_at, ip, user_agent, referer, status
FROM link_visits
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListLinkVisits(ctx context.Context) ([]LinkVisit, error) {
	rows, err := q.db.QueryContext(ctx, listLinkVisits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkVisitsPage = `-- name: ListLinkVisitsPage :many
SELECT id, link_id, created_at, ip, user_agent, referer, status
FROM link_visits
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListLinkVisitsPageParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListLinkVisitsPage(ctx context.Context, arg ListLinkVisitsPageParams) ([]LinkVisit, error) {
	rows, err := q.db.QueryContext(ctx, listLinkVisitsPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
