// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_visits.sql

package sqlcgen

import (
	"context"
	"time"
)

const countLinkVisits = `-- name: CountLinkVisits :one
SELECT COUNT(*)
FROM link_visits
`

func (q *Queries) CountLinkVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinkVisits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLinkVisit = `-- name: CreateLinkVisit :one
INSERT INTO link_visits (link_id, created_at, ip, user_agent, referer, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateLinkVisitParams struct {
	LinkID    int64
	CreatedAt time.Time
	Ip        string
	UserAgent string
	Referer   string
	Status    int32
}

func (q *Queries) CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLinkVisit,
		arg.LinkID,
		arg.CreatedAt,
		arg.Ip,
		arg.UserAgent,
		arg.Referer,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
