---
version: "2"

linters:
  default: standard
  enable:
    - gocyclo
    - revive
    - goconst
    - unparam

  settings:
    gocyclo:
      min-complexity: 10

    revive:
      rules:
        - name: blank-imports
