package handlers

import (
	"fmt"
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"

	"code/internal/domain"
	"code/internal/transport/httpapi/dto"
)

type CreateLinkRequest struct {
	OriginalURL string `json:"original_url" example:"https://example.com"`
	ShortName   string `json:"short_name" example:"abc123"`
}

type UpdateLinkRequest struct {
	OriginalURL string `json:"original_url" example:"https://example.com/updated"`
	ShortName   string `json:"short_name" example:"abc123"`
}

// ListLinks godoc
// @Summary List links
// @Description Returns all links. When range is provided, returns a page and includes Content-Range.
// @Tags links
// @Param range query string false "Range of items, format [start,count]. Max page size 1000." example([0,10])
// @Produce application/json
// @Produce application/problem+json
// @Header 200 {string} Content-Range "links 0-9/42"
// @Success 200 {array} dto.LinkResponse
// @Failure 400 {object} Problem
// @Failure 500 {object} Problem
// @Router /api/links [get]
func (h *Handler) ListLinks(c *gin.Context) {
	rng, query, hasRange, err := parseListRange(c.Query("range"))
	if err != nil {
		writeInvalidRange(c)
		return
	}

	var (
		items []domain.Link
		total int64
	)

	if hasRange {
		items, total, err = h.svc.ListPage(c.Request.Context(), query.Offset, query.Limit, true)
	} else {
		items, err = h.svc.ListAll(c.Request.Context())
	}

	if err != nil {
		h.fail(c, err)
		return
	}

	resp := make([]dto.LinkResponse, 0, len(items))
	for _, it := range items {
		resp = append(resp, dto.FromDomain(it, h.baseURL))
	}

	if hasRange {
		if len(items) == 0 {
			c.Header("Content-Range", fmt.Sprintf("links */%d", total))
		} else {
			end := rng.Start + len(items) - 1
			c.Header("Content-Range", fmt.Sprintf("links %d-%d/%d", rng.Start, end, total))
		}
	}
	c.JSON(http.StatusOK, resp)
}

// CreateLink godoc
// @Summary Create link
// @Description Creates a short link. If short_name is empty, it will be autogenerated.
// @Tags links
// @Accept application/json
// @Produce application/json
// @Produce application/problem+json
// @Param request body CreateLinkRequest true "Create link request"
// @Success 201 {object} dto.LinkResponse
// @Failure 400 {object} Problem
// @Failure 409 {object} Problem
// @Failure 500 {object} Problem
// @Router /api/links [post]
func (h *Handler) CreateLink(c *gin.Context) {
	var req CreateLinkRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		badJSON(c)

		return
	}

	link, err := h.svc.Create(c.Request.Context(), req.OriginalURL, req.ShortName)
	if err != nil {
		h.fail(c, err)

		return
	}

	c.JSON(http.StatusCreated, dto.FromDomain(link, h.baseURL))
}

// GetLink godoc
// @Summary Get link by ID
// @Tags links
// @Produce application/json
// @Produce application/problem+json
// @Param id path int64 true "Link ID" minimum(1)
// @Success 200 {object} dto.LinkResponse
// @Failure 400 {object} Problem
// @Failure 404 {object} Problem
// @Failure 500 {object} Problem
// @Router /api/links/{id} [get]
func (h *Handler) GetLink(c *gin.Context) {
	id, ok := parseID(c)
	if !ok {
		return
	}

	link, err := h.svc.Get(c.Request.Context(), id)
	if err != nil {
		h.fail(c, err)

		return
	}

	c.JSON(http.StatusOK, dto.FromDomain(link, h.baseURL))
}

// UpdateLink godoc
// @Summary Update link
// @Description Updates original_url. short_name is immutable; if provided and differs, returns 422.
// @Tags links
// @Accept application/json
// @Produce application/json
// @Produce application/problem+json
// @Param id path int64 true "Link ID" minimum(1)
// @Param request body UpdateLinkRequest true "Update link request"
// @Success 200 {object} dto.LinkResponse
// @Failure 400 {object} Problem
// @Failure 404 {object} Problem
// @Failure 409 {object} Problem
// @Failure 422 {object} Problem
// @Failure 500 {object} Problem
// @Router /api/links/{id} [put]
func (h *Handler) UpdateLink(c *gin.Context) {
	id, ok := parseID(c)
	if !ok {
		return
	}

	var req UpdateLinkRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		badJSON(c)

		return
	}

	link, err := h.svc.Update(c.Request.Context(), id, req.OriginalURL, req.ShortName)
	if err != nil {
		h.fail(c, err)

		return
	}

	c.JSON(http.StatusOK, dto.FromDomain(link, h.baseURL))
}

// DeleteLink godoc
// @Summary Delete link
// @Tags links
// @Produce application/problem+json
// @Param id path int64 true "Link ID" minimum(1)
// @Success 204 {string} string "No Content"
// @Failure 400 {object} Problem
// @Failure 404 {object} Problem
// @Failure 500 {object} Problem
// @Router /api/links/{id} [delete]
func (h *Handler) DeleteLink(c *gin.Context) {
	id, ok := parseID(c)
	if !ok {
		return
	}

	err := h.svc.Delete(c.Request.Context(), id)
	if err != nil {
		h.fail(c, err)

		return
	}

	c.Status(http.StatusNoContent)
}

func parseID(c *gin.Context) (int64, bool) {
	id, err := strconv.ParseInt(c.Param("id"), 10, 64)
	if err != nil || id <= 0 {
		writeProblem(c, Problem{
			Type:   problemTypeValidation,
			Title:  validationTitle,
			Status: http.StatusBadRequest,
			Detail: "invalid id",
		})

		return 0, false
	}

	return id, true
}
